Chapter10
8percent/tsd pull request #37
Opened 2017-08-06 14:32 UTC by anohk

resolve #34

2017-08-07 09:59 UTC, wayhome25 commented
우와..! 자료를 보니 이번주 스터디에 참여하지 못하는게 아쉽네요ㅠㅠ

2017-08-07 11:54 UTC, leehosung commented on chapter10/summary.md
> +- 메서드가 정의되어 있지 않으면 HttpResponseNotAllowed 예외 발생
흑흑 HttpMethodNotAllowed 가 아니었어

2017-08-07 16:06 UTC, leehosung commented on chapter10/summary.md
> +| DetailView | 객체를 삭제 |
DeleteView?

2017-08-08 13:38 UTC, snsn requested changes
바뀐 이미지와 오타만 수정하면 될 것 같습니다. 수고많으셨습니다.

2017-08-08 13:38 UTC, snsn commented on chapter10/summary.md
> +![old-new](./imgs/old-new.png)
old, new style이 바뀐것 같아요. 아래 이미지와

2017-08-08 13:38 UTC, snsn commented on chapter10/summary.md
> +	def form_vlaid(self, form):
Typo: fields = (... , 'scoops_remaining')
Typo: form_valid

2017-08-08 13:38 UTC, snsn commented on chapter10/summary.md
> +	def form_invlaid(self, form):
Typo: form_invalid

2017-08-08 13:38 UTC, snsn commented on chapter10/summary.md
> +	return super(FlavoerCreateView, self).form_invalid(form)
Typo: FlavorCreateView

2017-08-08 13:38 UTC, snsn commented on chapter10/summary.md
> +from vraces.views import LoginRequiredMixin
Typo: braces.views

2017-08-08 14:50 UTC, anohk commented
오타가 너무 많네요 ioi ㅎㅎㅎ

2017-08-08 16:17 UTC, ianstream approved these changes

2017-08-08 16:17 UTC, ianstream commented
고생하셨어요~

2017-08-09 00:07 UTC, snsn approved these changes

2017-08-09 02:37 UTC, merged