13장 요약
8percent/tsd pull request #48
Opened 2017-08-21 15:33 UTC by SeongKwonHa

2017-08-22 01:02 UTC, namongk requested changes
13장 요약인가요? 파일 경로는  chapter12로 되어 있어요. 확인 부탁드립니다.

2017-08-23 01:55 UTC, SeongKwonHa commented
다시푸시했습니다

2017-08-23 02:00 UTC, namongk commented on chapter13/summary.md
> +여기서 커스텀 타이틀, 기본 스타일시트아 추가 스타일시트, 기본 헤더, 서브헤더, 본문, 자식블록의 이용,
스타일시트아~

2017-08-23 02:00 UTC, namongk commented on chapter13/summary.md
> +  - title : Rwo Scoops of Django
Rwo

2017-08-23 02:01 UTC, namongk commented on chapter13/summary.md
> +  - 각 이터레이션 루프 때마다 얼마나 많은 프로세싱이 벌어지느가?
지느가?

2017-08-23 02:02 UTC, namongk commented on chapter13/summary.md
> +- 지금부터 나오는 피해야 할 몇 가지 주의사항을 살펴보자.
문장이 어색함

2017-08-23 02:02 UTC, namongk commented on chapter13/summary.md
> +- 간단한 템플릿 코드라도 상당한 프로세싱을 필요로 하는 객체가 호출되어 부하가 상당한 부하를 일으킬 수 있다.
부하가 상당한 부하가

2017-08-23 02:02 UTC, namongk commented on chapter13/summary.md
> +- 많은 양의 이미지나 데이터를 처리하는 프로제긑는 뷰나 모델, 헬퍼 메서드, 또는 셀러리 등을 이용한 비동기 메시지 큐 시스템으로 처리해야된다.
프로제긑

2017-08-23 02:04 UTC, namongk commented on chapter13/summary.md
> +- 이용 한다면 html파일을 확장하여 이용하면 {{ block.super}}를 이용해 템플릿들을 관리할 수 있다.
이용한다면?

2017-08-23 02:05 UTC, namongk commented on chapter13/summary.md
> +- implicit한 {{object}}, {{object_list}} 대신에 explicit한 {topping_list}}, {{toppin}}을 이용할 수 있다.
암묵적인, 명시적은 등과 같이 한글도 병기하는건 어떨까요?

2017-08-23 02:05 UTC, namongk commented on chapter13/summary.md
> +#좋은 예(URLConf 파일 안의 이름을 참조하는 %url 태그이용)
%url 오타?

2017-08-23 02:05 UTC, namongk commented on chapter13/summary.md
> +- TEMPLATES 세팅의 OPTTIONS에서 string_if_invalid 옵션을 설정함으로써 좀 더 자세한 에러 메세지를 받아 볼 수 있따.
OPTTIONS 오타?

2017-08-23 02:05 UTC, namongk commented on chapter13/summary.md
> +- TEMPLATES 세팅의 OPTTIONS에서 string_if_invalid 옵션을 설정함으로써 좀 더 자세한 에러 메세지를 받아 볼 수 있따.
있따!

2017-08-23 02:06 UTC, namongk requested changes
수정 부탁드립니다.

2017-08-23 02:12 UTC, SeongKwonHa commented
수정하였습니다

2017-08-23 05:55 UTC, namongk approved these changes
리뷰했습니다. 마지막 스터디! 즐겁게 마무리 해요!

2017-08-23 05:55 UTC, merged